name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build_test_sonar_nexus:
    name: Build + Sonar + Nexus
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build with Maven
        run: mvn -B clean verify

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=spring-github \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Deploy to Nexus
        run: mvn deploy -DskipTests
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  docker:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: build_test_sonar_nexus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

